# Generated by Django 5.2.5 on 2025-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation2',
            name='payment_method',
            field=models.CharField(choices=[('mobile', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=20),
        ),
    ]
