# Generated by Django 5.2.4 on 2025-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(help_text="FontAwesome icon class, e.g. 'fas fa-users'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display on homepage')),
            ],
            options={
                'verbose_name': 'Impact Stat',
                'verbose_name_plural': 'Impact Stats',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['created_at'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
