# Generated by Django 5.2.4 on 2025-07-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_impactstat_alter_teammember_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactstat',
            name='icon',
        ),
        migrations.AddField(
            model_name='impactstat',
            name='image',
            field=models.ImageField(blank=True, help_text='Background image for the stat card', null=True, upload_to='impact_stats/'),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='value',
            field=models.CharField(default='', help_text="Stat value, e.g. '11+', '60%+', '$600,000+'", max_length=50),
        ),
    ]
