# Generated by Django 5.2.4 on 2025-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_impactstat_icon_impactstat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for resource card', null=True, upload_to='resources/images/'),
        ),
    ]
