# Generated by Django 5.2.4 on 2025-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teammember_facebook_url_teammember_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
