# Generated by Django 5.2.4 on 2025-08-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_teammember_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supporters/')),
            ],
            options={
                'verbose_name': 'Supporter',
                'verbose_name_plural': 'Supporters',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='impactstat',
            options={'ordering': ['order'], 'verbose_name': 'Impact Stat', 'verbose_name_plural': 'Impact Stats'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='impact_stats/'),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='impactstat',
            name='value',
            field=models.CharField(help_text="E.g. '10K+', '85%'", max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/'),
        ),
    ]
